### ISSUE TITLE
Evil wizards are.. Etherial? for me

### ISSUE THREAD

**Issue by Xeredek** [Electroblob77/Wizardry#100]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Singleplayer

Issue details: 
It seems evil Wizards aren't spawning in their towers correctly for me. Essentially- When they spawn in, I can hear them, they can move around, harm the player, and are generally functional. However, they're always totally invisible- and turning on visible hitboxes shows that they don't actually even have one (?). No idea, can't think of any mods that might be causing this but it's been consistent for me so far.

**Comment by Electroblob77** [comment]
That's very weird. Sounds like the wizard only exists server-side, normally reloading the world would fix that but I'm guessing that hasn't worked for you. Visible hitboxes won't help you here because they too require the client to know about the entity (in fact, they're pretty useless for debugging anything other than rendering issues).

Does this happen if you spawn the evil wizard in with a spawn egg? And are regular wizards unaffected? I'll need to try and narrow this down to figure out what specific thing about your setup is causing problems.

**Comment by Xeredek** [comment]
Oh dear... Ya know, I hadn't actually tried that, and it seems to have worked. Now I feel incredibly foolish, the possibility completely flew over my head. 
It's still a weirdly consistent thing, but much less of a problem than I initially thought then. :0
I tested it, they spawn just fine under every circumstance aside from in their towers, so it's definitely tied to that, and only effecting the evil dudes. If it matters- I have Recurrent complex, dungeon tactics, and ice and fire all, and biomes'o plenty in this current build, all of which fiddle with generation a good bit.

**Comment by Electroblob77** [comment]
Right, so it's a worldgen issue. I'll be doing some work on worldgen in the not too distant future so I'll look into it then. If you feel like investigating further, try removing those mods you listed one-by-one and generating a new world each time, and see if it still happens (set the tower rarity to 1 to make it easier to test).

**Comment by Ghostrider231** [comment]
Had something like this during a modded Playthrough last year (2018).
When I encountered something like this, you could only harm them with a blackhole spell, summons, or Splash Damage Spells.

Otherwise, your details pretty much describes exactly what I have.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
