### ISSUE TITLE
Server hang ArcaneWorkbench

### ISSUE THREAD

**Issue by bigenergy** [Electroblob77/Wizardry#116]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Server 

Issue details: server hand

Log report https://pastebin.com/vhScB402
Crash report https://pastebin.com/yim3emkP

**Comment by Electroblob77** [comment]
Okay, what's happened there is that the server has received a packet telling it that the apply button was pressed in an arcane workbench, but the player that sent it was not using an arcane workbench. I should have added a safety check which logs a warning, but really this should never happen so something weird is going on.

> Electroblob's_Wizardry-4.1.4[fixes-big_energy].jar

I notice you are using a custom jar file which presumably contains fixes you have added yourself. Please could you give details of what exactly these fixes are, in case one of them has caused the problem?

**Comment by bigenergy** [comment]
> I notice you are using a custom jar file which presumably contains fixes you have added yourself.

In my correction, I just turned off the scrolls that I do not need.

**Comment by bigenergy** [comment]
I would like to offer the ability to disable unnecessary scrolls in the config, it is very convenient

**Comment by Electroblob77** [comment]
You can turn off unwanted spells in the config file already, but I'm guessing you want to keep the books but not have the scrolls. The good news is that this feature is coming in the next release, so stay tuned!

**Comment by bigenergy** [comment]
Please fix it.
My server crashes every day several times because of this :(

**Comment by bigenergy** [comment]
@Electroblob77 pls fix

**Comment by Electroblob77** [comment]
Please don't ping me just to request a fix. I can't simply upload a new patch every time someone reports an issue, especially since as far as I'm aware, nobody else has this issue and it shouldn't be happening anyway. However, since you seem to know a bit about modding, you are welcome to temporarily fix this yourself: add an `if(player.openContainer instanceof ContainerArcaneWorkbench)` check around [this line](https://github.com/Electroblob77/Wizardry/blob/1.12.2/src/main/java/electroblob/wizardry/packet/PacketControlInput.java#L39). Compile the jar and drop it into your server and it'll fix the problem.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
