### ISSUE TITLE
Hard crash cant load back into world Grinder/Crusher wizard

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#124]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: All (Single and multy)

Issue details: Evil wizard or his spell entities when attacked by a grinder/mob crusher/slaughter factory cause a crash could also be that they try to target these machines for some reason and then crash.

Other mods involved: https://minecraft.curseforge.com/projects/industrial-foregoing https://minecraft.curseforge.com/projects/draconic-evolution?gameCategorySlug=mc-mods&projectID=223565 

Link to crash report (if applicable): https://pastebin.com/Ee7AZbhb

**Comment by Electroblob77** [comment]
Looks very similar to #93, but the difference here is that the wizard is directly targeting the mob grinder rather than it just being a revenge effect. Thing is, the targeting methods are part of vanilla and therefore Forge fake players shouldn't be affected. I think there's a fix I can do, but I'm confused as to why my code specifically would cause this error. Thanks for reporting.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
