### ISSUE TITLE
Light Spell Entity randomly spawns within forests

### ISSUE THREAD

**Issue by DivideEtImperia** [Electroblob77/Wizardry#128]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.7.10 [change as necessary]  
Wizardry version: 1.1.5 [change as necessary]
Environment: Server [delete as necessary]

Issue details: Within any forest, there is a bug where the light spell entity randomly spawns within forested biomes. After removing the texture for the light spell, the problem increasingly worsened. https://cdn.discordapp.com/attachments/476455559927955476/561227954118590486/2019-03-29_19.40.07.png

An image of the bug without the light spell texture.

Other mods involved: Possibly Thaumcraft.

**Comment by Electroblob77** [comment]
Looks like there are two issues going on here. I can see the light block (it's not actually an entity) is growing to a huge size, this is due to issue #101. Removing the texture won't make any difference other than making the bug even more obvious because of the pink and black squares.

However, you're saying the block is appearing randomly in forests as well, which I assume means you didn't put them there. Since this is 1.7.10 you may have an ID conflict causing them to generate where there ought to be other blocks, or perhaps if you changed your modlist after creating the world. Could you try creating a new world and flying around a bit (don't cast the light spell at all) to see if you can replicate this issue?

**Comment by Electroblob77** [comment]
I think I was told this was solved via Discord (it was an ID conflict I think). Please reopen if this is not the case.
