### ISSUE TITLE
[Suggestion] Have Arcane Jammer affect Evokers

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#130]
Now i don't know if evokers are affected by the arcane jammer spell. But I do like to point this out so that nobody else has to.

I do believe evokers should be affected by the arcane jammer spell too. Cause the fact that they also cast spells as well. (**Two uncastable Necromancer spells: Vex Swarm and Fangs**)

If the evoker was inflicted by said Arcane Jammer, then they should always be fleeing and cannot fight back during the spell's duration.

**Comment by Electroblob77** [comment]
> Two uncastable Necromancer spells: Vex Swarm and Fangs

...you read my mind! I've done Vex Swarm and Fangs is in the works.

Having evokers affected by arcane jammer is a neat idea, I like it. Currently that spell is of limited use in singleplayer so that would help make it more useful, thanks for the suggestion. (Leaving this thread open to remind me to implement it!)

**Comment by Electroblob77** [comment]
Added in the 4.2.0 release.
