### ISSUE TITLE
[Suggestion] Certain Looking-at-block spells could be more not-looking-at-block spells.

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#132]
I'm just going to post this here before this suggestion gets lost.

**(Digged directly into the curseforge's comments before it was lost)**

By the way, would it be possible to have it where you can cast certain spells like: Blizzard, Detonate, and Cobwebs [There's probably more] not require looking at a block like when you cast the Blackhole Spell? It would definitely make some of them more usable against Airborne type Monsters. Well for Lightning Bolt could it also require a target too? Was sorta curious cause i've seen wizard mobs doing this.

**(end of digged directly)**

Would it be possible to have the spells like I've explained above be castable without looking at a block? Like the blackhole spell. Again I've Explained pretty much everything above.

Morelike, I would like to see these spells work with a direct target too.

**Comment by Electroblob77** [comment]
> i've seen wizard mobs doing this

This is because they actually use a different system: they don't 'aim' like the player does, they just use their AI target directly.

Anyway, I've done a massive overhaul of the spell code in my dev branch which includes improvements to aiming for these kinds of spells, so you'll see some changes to them in the next release (black hole and blizzard definitely allow mid-air casting now, not sure about the others off the top of my head).

**Comment by Ghostrider231** [comment]
Guessing the other spells also work with direct targets too? Although i can see some of these spells at least requiring looking a block to work if there isn't a direct target in sight. (eg. Lightning bolt and cobwebs)

(Sorry, if i sound too much)

otherwise looking forward to the feature update! (Loving the new spell gui, I can finally see what spell is after or before it.)

**Comment by Electroblob77** [comment]
I'm going with whatever makes most sense for each spell, essentially, so most of them will probably do what you expect them to.

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
