### ISSUE TITLE
[Suggestion] Enchantment descriptions

### ISSUE THREAD

**Issue by fivelol** [Electroblob77/Wizardry#135]
https://minecraft.curseforge.com/projects/enchantment-descriptions 
This mods adds descriptions to the lore of enchanted books, describing what the applied enchantment does, it appears this mod has enchantments but I don't know what they do, which is why I'm suggesting this. Thanks for the awesome mod

**Comment by Electroblob77** [comment]
That's because they shouldn't appear on enchanted books at all, they're the temporary ones used by imbue weapon and other similar spells. Could you tell me which game version you are using, so I know where to look for that issue?

**Comment by fivelol** [comment]
Forge version: 14.23.5.2815
Electroblob's Wizardry 4.1.4
I forgot to mention that I saw them in JEI and not in normal gameplay, so here's my JEI version
1.12.2-4.15.0.268

**Comment by Electroblob77** [comment]
Ah, that makes a difference then, thanks for that information. JEI presumably goes through all registered enchantments and displays a book for each of them, and unfortunately the Minecraft/Forge source has no way of specifying that an enchantment may not appear on books (wizardry has to forcefully remove them as they are generated, it was discussed in PR #121 if you're interested). There may be a way to tell JEI not to display them, I'll have a look, but if not there is little I can do about it, sorry.

I'm considering submitting a PR to Forge to add a hook for this because I'd rather not do hacky fixes if I can avoid them.

**Comment by Electroblob77** [comment]
Confirmed as a bug in Forge: https://github.com/MinecraftForge/MinecraftForge/issues/5625

**Comment by Electroblob77** [comment]
Enchantment descriptions using the WAWLA system have been added in 037f340, see #210
