### ISSUE TITLE
[Suggestion] Enchantability on Wizard Robes

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#139]
As far As I remember, The Wizard Robes weren't intended to be enchanted.

I think It would be nice to have the robes enchantable via enchantment table. And cause the fact that the wizard robes work perfectly fine with enchantments. (I can recharge it and/or upgrade it to legendary both via arcane workbench without it breaking the enchantments)

Recharging the robes via crafting with a magic potion breaks the enchantments. (Haven't tested this one myself)

At the moment, Wizard Robes can only be enchanted via anvil.

**Update:** Wizard robes can be recharged with mana flasks (via crafting) without it breaking the enchantments.
(I don't know If I should rename this to: Allow Wizard Robes in the Enchantment Table)

**Comment by Electroblob77** [comment]
>Recharging the robes via crafting with a magic potion breaks the enchantments.

I wasn't aware of that but it would make sense since I was not expecting them to have any enchantments in the first place. That's a bug that will need fixing.

As mentioned in the discussion over on Discord, this needs changing one way or the other, thanks for logging it here. I want to add more ways of upgrading wizard armour, and rather than reinvent the wheel it makes more sense to allow enchantments and add a few magic-based ones. I'm also planning on making fancy textures for legendary armour instead of showing the enchantment glint.

Related to this, I also need to stop wands being enchanted with sword enchantments in an anvil.

**Comment by Ghostrider231** [comment]
OK I've just tried recharging my robes via crafting with magic potion, and oddly enough, the enchantments **actually stay...**

**Comment by Electroblob77** [comment]
Added in the 4.2.0 release. Wizard robes are now fully enchantable, and a few new magic-related protection enchantments have been added as well.
