### ISSUE TITLE
Crash after adding creature to the immunity list

### ISSUE THREAD

**Issue by belathus** [Electroblob77/Wizardry#141]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Server

Issue details: I added creatures to the elemental immunity list. When the server started, it crashed. Admittedly, I thought this problem had been fixed after #31 and #49. I'm pretty sure the entity IDs are correct (I copied them from the output of ```/ct entities``` command).

Here is the commit that caused the crash: https://github.com/belathus/Wanderlust-Renewed/commit/17729e6ea8669646e19e40dee43c6bedc6db5e86#diff-1ee1f4a52c71b39c94f28e257ae87dd5

Other mods involved: Twilight Forest, Mowzie's Mobs

Link to crash report: https://gist.github.com/belathus/4c5a623b1a02894dd419185d96c0df31

**Comment by Electroblob77** [comment]
That's because the fix for #49 was committed after 4.1.4 was released: https://github.com/Electroblob77/Wizardry/compare/4.1.4...1.12.2

Pro tip: if you look at a commit (97a23d0 in this case) it shows which branches and releases it's in just below the commit name and description.

A quick look at that crash report confirms that the crash occurred during a call to Arrays.asList, which was removed in that commit.

**Comment by belathus** [comment]
I guess I assumed we had a more recent release. My bad.
