### ISSUE TITLE
Silverfish Swarm truly multiplies until the game runs out of memory from too many mobs and particles.

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#143]
forge-14.23.5.2838 
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer/LAN game/Server/ALL of them

Issue details: I spawned a silverfish swarm and every time they killed something they spawned a new silverfish sometimes even more than one. This caused there to be and endless amount of them at some point freezing the game especially the moment they decided to fight each other.
This happens with no mods installed other than this one. I tested it. (You probably don’t notice it too much as they don’t do much dmg)

But this is a huge problem on my Modpack as the spells have x10 dmg to be usable on the scaling health of mobs that goes up to 600HP for a normal zombie at some points.

As they start decimating mobs they spawn new ones so fast you can’t do anything and once they start going at each other its over they spawn like there is no tomorrow and fps drops t0 0 especially with the particles they needlessly have. Crashing the game from running out of memory!

Was tested with just this mod installed after a player of my pack reported this bug. Still happened even with just the mod and nothing else.

Other mods involved: [only list mods that are relevant to the problem]

Link to crash report (if applicable): https://pastebin.com/7KdQjtai  here this is the report of the user

**Comment by Ghostrider231** [comment]
Hello I'm not the author,

**Silverfish spawning on kills is intentional.** (It's mentioned in the wiki from curseforge: _**Summons a swarm of silverfish to fight for you. When a creature is killed by the silverfish, it spawns 1-4 more silverfish.**_)

(The wiki here doesn't have info about silverfish swarm because the author didn't move that here, although the spell book is rather vague about the description)

Although, it would be convenient for feature update 4.2 to introduce a summon cap _option_ with spell jsons.

**Do you by any chance have minion revenge targeting enabled? If so, that could explain the silverfish minions fighting each other.**

**Looks like you've mentioned scaling health in your modpack? If so, are silverfish minions killing everything very rapidly?**

**If they are, you could probably add the silverfish minions _(ebwizardry:silverfish_minion)_ in the scaling health blacklist and blight blacklist (if you have blights enabled)**

They may be very weak from that, but it does lessen the spawning from silverfish minions.

**Comment by SirAron111** [comment]
Thx for the info yes i already set them in the blacklist for scaling hp but since i upped the damage that magic spells do to 10 times the normal dmg if a player finds the spell early in game they rush every mob and since i have so many enemies spawning they literally multiply infinitely XD.

No revenge target is turned off on all mods on the pack even friendly fire is turned off. But ye the mod is super awesome but a more detailed documentation in the wizardry book would be nice. As well as some extra config for some spells to balance them out for packs. Good to know its intentionally the mod maker probably wasn’t prepared for special cases where mobs would die from silverfish so fast they had no time to fight back to cull the horde that would then just grow and grow.

Defo needs some caps, config and the like. Hope these features will come to prevent things like this. For now I disabled the swarm spell. Sadly it was one of my favorites and also the favorite of the user sending the report.

**Comment by Electroblob77** [comment]
I can confirm that spawning more silverfish is the intended behaviour of the spell, but as you say, I didn't anticipate this kind of corner case! It sounds like it could use a limit to the number of 'generations' of silverfish so that eventually they all disappear. It would also benefit from a 'swarm logic' fix so that they don't attack each other, as in #75.

Additionally, you will be able to tune the number spawned, lifetime, attack damage etc. in the next update through spell JSON files.

For now I guess your best bet is to either fiddle with the damage settings so that they don't kill stuff as fast, or more likely just disable the spell for the time being.

**Comment by Electroblob77** [comment]
The fix detailed above has been implemented in the 4.2.0 release.
