### ISSUE TITLE
Crash after upgrading wand

### ISSUE THREAD

**Issue by paulthetic** [Electroblob77/Wizardry#155]
Minecraft version: 1.12.2 
Wizardry version: 4.1.4 
Environment: Singleplayer

Issue details: When I upgraded my wand to apprentice, it crashed and now I can't load my world.

Other mods involved: 

Link to crash report (if applicable): https://paste.dimdev.org/obuxoxizox.mccrash

**Comment by Electroblob77** [comment]
Looks a bit like issue #90, but that was fixed in 4.1.4. I can add a check to fix the problem, but I'd like to know why it happened in case something is going wrong further back. When you upgraded the wand to apprentice, did it have any spells bound to it? Had you just crafted it, or did you use it before upgrading it? Did you edit the wand's NBT data? Hopefully this information might help me to reproduce the crash.
