### ISSUE TITLE
When player dies the game crashes; cannot load the game afterwards.

### ISSUE THREAD

**Issue by stormbringerGT** [Electroblob77/Wizardry#162]
Minecraft version: 1.12.2
Wizardry version: 4.1.4
Environment: Singleplayer

Issue details: Was fighting a Skeleton with a bow and died. As the option to respawn came up the game crashed. This crash also prevents loading back into that world as well.

Other mods involved: This is a similar error I had before and was unable to trace, it could be related to [Tomb Many Graves 2](https://www.curseforge.com/minecraft/mc-mods/tomb-many-graves-2), since that would trigger on my death?

Link to crash report (if applicable):
https://pastebin.com/Yjjp0a3S

**Comment by Electroblob77** [comment]
That looks almost identical to your previous issue, and it will be covered by the fix for that. I don't know why it's happening for a vanilla skeleton, I can only assume that one of the mods you have is fiddling with entity drops (for any entity) and adding null items, which it shouldn't be doing. This would suggest special mobs' involvement in the last crash was a coincidence.

If you like, you can investigate this further by removing mods (except wizardry) until it doesn't happen any more. That way you'll know which mod is causing it, and if it's open source then I can take a look at its code and see what's going wrong.

P.S. Please don't close this issue, it will happen automatically when the fix is released.

**Comment by stormbringerGT** [comment]
Will do some testing on my end and let you know what is happening.

The strange thing is, it happens when I die, not when I kill a mob.

If it is a compat issue on Special mobs side, I'll drop that in a heart beat, the variation in mobs isn't worth the loss of this this mod.

**Comment by stormbringerGT** [comment]
Okay so i started with mods I think might be offenders, Elctroblob, Special Mobs and Tombstone.

Died multiple times with no crashes.

So I added back in Half of my mod list and got this crash. So at least now I have a half to narrow down (will add remove half of this half, etc). I"ll report the crash report as well each time, incase that data is useful to you and you can gleam some gems.

https://pastebin.com/DxZSZc6K

**Comment by stormbringerGT** [comment]
So I added in 20 mods and got the crash again, this time by a vibrant journeys skeleton knight with your mod, but Vibrant Journys wasn't one of the 20 added, but at least now I have a smaller list to sift through!
https://pastebin.com/Nv1rn1mD

**Comment by stormbringerGT** [comment]
Okay nailed it down. So Electroblob's Wizardy and [Tool Belt](https://www.curseforge.com/minecraft/mc-mods/tool-belt) cause a crash when I die. What a weird issue to have haha, but at least it is found. Will post on his git as well. Thanks for dealing with my spam as I worked through this!

https://pastebin.com/3if6t5kQ

**Comment by stormbringerGT** [comment]
Sorry not sure how to link related bugs:
https://github.com/gigaherz/ToolBelt/issues/39

**Comment by stormbringerGT** [comment]
Will wait for you to close, but the issue was caused because when I downloaded the Tool Belt mod from curse it didn't grab the newest version. Thanks for being patient with me!

**Comment by Electroblob77** [comment]
That makes sense, thanks for taking the time to investigate!
