### ISSUE TITLE
Ice spike and Minion Revenge Ticking Entity Crash

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#188]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Server (All Environments)

Issue details: 

When I started this mod trying out the new update, I first started a world where I messed around and spawned lots of wizards and evil wizards that fight each other. During this, I had two crashes which both ended giving the ticking entity crash.

The First Crash was the Ticking entity crash with Ice Spikes. (Done with only this mod installed)
The Second Crash was the Ticking entity crash for Minion Revenge targetting.

Other mods involved: 
For the First one, no other mods involved.
The Second doesn't really mention any other mods. So i assume this could be done with this mod alone.

Link to crash report (if applicable): 

First Crash: https://pastebin.com/KDHYCMw9
Second Crash: https://pastebin.com/YATriHLb

**Comment by Electroblob77** [comment]
Pretty sure those two crashes are completely unrelated. The ice spikes one makes sense, I can see what's gone wrong there.

The second one is definitely the same crash as #185, ~~but I don't see how anything on that line can be null at that point. I'll have to do some testing myself with wizards using summon zombie.~~

Edit: Never mind that I just worked it out! Will fix both issues for the next update.

**Comment by SirAron111** [comment]
https://pastebin.com/FfnWuAtH As for the ticking entity i got one like that as well. Revenge targeting from summons and especial from the mobs spawned via the obelisk spawners like in this crash will crash the game. It happens when you hit them with spells or so but mostly when you they get hit by something else like getting stuck and suffocating gives this crash or when they get dots you can’t revenge target poison bombs XD. Well anyway I had this exact crash many times with obelisk spawner isummoncreatures like blazes and the electric blazes etc (side note i have summons targeting player or revengetargeting player when you hit them turned off in the configs of ebw)

**Comment by drakray** [comment]
Hi there, I got a Ticking Entity Crash with Ice Spike by a Backfired scroll, using EBW 4.2.5 for 1.12.2
[CrashLog](https://pastebin.com/2FKrwWx1)
