### ISSUE TITLE
ArrayIndexOutOfBoundsException caused by spells sound category

### ISSUE THREAD

**Issue by DoctorZoe** [Electroblob77/Wizardry#198]
Minecraft version: 1.12.2
Wizardry version: Electroblob's Wizardry - 4.2.1
Environment: Singleplayer/Server

Whenever I cast life drain, whether through scrolls or wands, it crashes the game.

Other mods involved: [only list mods that are relevant to the problem]
Link to crash report (if applicable): https://pastebin.com/4PLHHJtq
[drain life error.txt](https://github.com/Electroblob77/Wizardry/files/3525122/drain.life.error.txt)

**Comment by Electroblob77** [comment]
As you can see from the above, this has been reported a lot! The crash is caused by the way I'm adding the spells sound category. I've seen it in a variety of different forms but it's always the same underlying cause. The code that adds the sound category isn't actually mine, I borrowed it (with credit) from a forge forums post, but clearly there's something wrong with it.

I'll see if I can get to the bottom of it ASAP, it's obviously affecting a large number of players.

**Comment by JWTHDYTWA** [comment]
`Electroblob77 closed this in 931c996` 4.2.2, the issue is still present.
