### ISSUE TITLE
Stereo Sound File/Directional Audio Problems

### ISSUE THREAD

**Issue by TechnoMysterio** [Electroblob77/Wizardry#218]
Minecraft version: 1.12.2
Wizardry version: 4.2.1
Environment: Singleplayer, although applicable in all cases

Issue details: With the audio in the mod, a minor yet somewhat irritating problem is present in the fact that the sound effects for the various spells, mobs and the like are not directional. To be more specific, if, for instance, a mob standing to the side of the player plays a sound effect, that sound will play in both ears without having the audio pan to the side, unlike with sound effects from vanilla.

The problem comes about from the fact that Minecraft's audio engine will always play stereo sound files in both ears, even if the sound in question is to the side of the player. This makes it good for things like music or for big, impactful events that happen around the player (like the Wither summoning sound from vanilla), but not for things like mobs, machines, or in this case, things like spells being cast in an area or by other players. Therefore, the way to solve the problem is to convert all the sound files from the mod that sound be directional (so most of the sound effects from what I can tell) from stereo to mono. Doing this would also cut down on the filesize of the mod too, since you're essentially halving the amount of data used by the sound files.

This is a fairly common problem with mods that add custom sound effects, and it took me a while to discover it myself when I was doing sound design for other mods. It's fairly subtle, but fixing this could help improve the overall polish of the mod, since it'll make sure that the custom sounds actually feel like they're coming from within the world.

As a final question regarding the sounds for the mod, how were they made, or where did they come from? They're all rather good, and I always find it interesting to see where other people get their sounds from, so it'd be helpful to know their sources.

**Comment by Electroblob77** [comment]
Interesting, today I learned! I suppose I haven't noticed it because most of the spell sounds get played at the player's location, and I mostly test in singleplayer, so the lack of directionality is unnoticeable. I will go through and convert them all to mono (except for perhaps the spellbinding in the workbench, that should probably be stereo).

Some of the sounds use the vanilla assets, sometimes with the pitch altered in the code (of course, I can't distribute the vanilla sound files themselves so there's a limit to what I can do with them).
The rest are either from places like freesound.org and youtube, or I've made them from scratch using a synthesiser and some post-editing in Audacity - or a combination of the two.
