### ISSUE TITLE
[1.12.2] Modtweaker Interaction: Bad Texture returned.

### ISSUE THREAD

**Issue by MokahTGS** [Electroblob77/Wizardry#27]
Minecraft version: 1.12.2
Wizardry version: 4.1.1
Environment: Singleplayer

Issue details: Adding the crystal flower to a Botania Modtweaker recipe produces a flower with a bad texture.

Other mods involved: Modtweaker?
Mod List: https://pastebin.com/TfqRaPqm

https://www.dropbox.com/s/dgmhkxzy8q43e1s/2018-05-08_13.02.45.png?dl=0

https://www.dropbox.com/s/63p48kn5s00uq4n/2018-05-08_13.02.58.png?dl=0

**Comment by Electroblob77** [comment]
Hmmm, interesting. Normally this would be caused by a metadata issue, but I can't see anything wrong in that tooltip. Could you post the relevant line(s) of your modtweaker script?

Edit: Also, besides having a missing texture, does the crystal flower work otherwise? Can it be placed, and if so, does the placed block have the correct texture? Can you craft it into magic crystals?

**Comment by MokahTGS** [comment]
> mods.botania.ManaInfusion.addInfusion(<ebwizardry:crystal_flower:1>, <botania:flower:*>, 3000);

**Comment by Electroblob77** [comment]
I think ebwizardry:crystal_flower:1 is giving you a flower with metadata 1 rather than stack size 1. Try ebwizardry:crystal_flower * 1 instead

**Comment by MokahTGS** [comment]
`mods.botania.ManaInfusion.addInfusion(<ebwizardry:crystal_flower:* 1>, <botania:flower:*>, 3000); `

This does not work.

Changed the script to:

`mods.botania.ManaInfusion.addInfusion(<ebwizardry:crystal_flower:*>, botania:flower:*, 3000);`

and the code works, but the problem persists.

Took out Optifine just to see, but nothing changed.

Update: Fixed - My bad...

`mods.botania.ManaInfusion.addInfusion(<ebwizardry:crystal_flower>, <botania:flower:*>, 3000);  //3000 is the same as mana steel`

Took out the * that was giving it some weird meta data.  Whoops.
