### ISSUE TITLE
Randomly crashed a server

### ISSUE THREAD

**Issue by Moyye99** [Electroblob77/Wizardry#281]
Minecraft version: 1.12.2 
Wizardry version: 4.2.5
Environment: Server

Issue details: Exploring the world. Looked at a polar bear, it looked at me and the server crashed.
After it crashed, the VanillaFix mod told me that it was ElectroBlob's that caused the problem
Other mods involved: World of Dragon mod pack. 

Link to crash report (if applicable): 
https://pastebin.com/kwsMFHRQ
 or
[crash-2019-10-15_19.20.26-client.txt](https://github.com/Electroblob77/Wizardry/files/3731822/crash-2019-10-15_19.20.26-client.txt)

**Comment by Electroblob77** [comment]
That can't possibly be a server crash, it's a client crash. It also has nothing to do with polar bears! Are you sure it's the right crash report? (You'll need to get it from the server for a server crash)

The crash you've posted is because a spell is missing its properties file, or the file contains invalid JSON. You must have been holding a wand for that crash to happen, so whichever spell was equipped on it is the one that's got problems with its file. Your log should contain details of any JSON errors, try looking through it to find the problem.
