### ISSUE TITLE
Holoinventory Compat Issues

### ISSUE THREAD

**Issue by mxnmnm** [Electroblob77/Wizardry#289]
Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer

Issue details: Holoinventory's holograms are muted and make it difficult to see what's in the inventory.  It's similar to the issue with the neat health bars so the same issue is probably causing it.

Other mods involved: holoinventory

Link:
https://imgur.com/a/sT1jxuR

**Comment by Electroblob77** [comment]
Yes, this will be another OpenGL state issue like #170. As I explained in that issue, it's difficult to know what's causing it because there are so many things that modify the GL state, and there's no convention on what state it should be left in. I will investigate it but it's a very difficult one to fix.

**Comment by Electroblob77** [comment]
Presumed fixed in 4.2.6. Please reopen if the issue persists.
