### ISSUE TITLE
Flame Ray ignores Damage Immunity TImers with Potion Core Installed

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#30]
Minecraft version: 1.12.2
Wizardry version: 4.1.1  
Environment: All

Issue details: When you have Potion Core Installed alongside with this, default config provided. Flame Ray goes from balanced to Insanely OP. Any Mob getting attacked by flame ray inflects constant damage every tic. Instead of every 60 tics? 

**Although, setting "Separate Invulnerability Timers" to false from Potion Core's config makes flame ray behave normally again.**

Like I said, this can easily be worked-around from what I've said above. (So hopefully, nothing to fix, but to point out)

Other mods involved: Potion Core

**Comment by Electroblob77** [comment]
Ah great, thanks for this.

What's happening is that flame ray (or any continuous spell, for that matter) attempts to damage mobs every tick, but because of the invulnerability timer this doesn't normally cause any trouble. However, it looks like potion core is just straight up removing that invulnerability timer (or doing something weird, at least), hence the damage succeeds every tick.

The workaround you mentioned presumably undoes this change, fixing the problem, but you might notice some side effects with potion core itself, they obviously did it for a reason.

The answer is that I should be less lazy and check whether the entity is invulnerable before I damage it, and potion core should probably pay more attention to the side effects of messing with Minecraft's damage system. I'll fix it on my end for the next patch.

**Comment by Electroblob77** [comment]
[This comment](https://minecraft.curseforge.com/projects/potion-core?comment=31) on the potion core curseforge page describes this exact issue occurring, but with lycanite's mobs instead of wizardry. Tmtravlr's reply suggests that the config-based workaround is the intended solution, so without any up-to-date source for potion core the best option is to leave this for now and point people to the workaround if they experience the same issue.

**Comment by Electroblob77** [comment]
Just some housekeeping, no point keeping this open.
