### ISSUE TITLE
Artifacts not working/unintended effects

### ISSUE THREAD

**Issue by Darkveld** [Electroblob77/Wizardry#303]
Minecraft version: 1.12.2  
Wizardry version: 4.2.2 
Environment: All

Issue details: Ring of Chaining attacks player, Bottomless Provisions doesn't do anything at all, Amulet of the Immortal gives you a resurrect button that doesn't work, possibly more but these are the only ones I've had a chance to try so far.

Other mods involved: Happens even with only Wizardry installed

**Comment by Electroblob77** [comment]
Do you mean the ring of chaining attacks the player wearing it, or just other players? If it's the player wearing it, that is a bug. Otherwise, it will attack other players if they aren't your allies, that's intended.
Bottomless provisions _does_ work, you need to have a wand with replenish hunger on your hotbar, then it will cast it automatically when you are hungry.
Amulet of the immortal is know not to work in some cases, see #178.

**Comment by MoriyaShiine** [comment]
Can confirm that Bottomless Provisions does nothing whatsoever. I have a Master Healer Wand with Replenish Hunger in the first slot, with the wand in the first slot of my hotbar, and nothing happens.

**Comment by cornehoskam** [comment]
Can confirm that the Bottomless Provisions bauble does nothing as of right now.
