### ISSUE TITLE
Empowering Presence, unlimited power

### ISSUE THREAD

**Issue by KamiSami** [Electroblob77/Wizardry#317]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.5
Environment: Singleplayer/LAN game/Server, assuming this happens in all of them

Issue details: You can empower yourself with Empowering Presence for unlimited times, causing you to get more and more and more stronger the more you use it, you can become pretty much one-shotting wizard with any magic or unkillable with some spells.

Other mods involved: I don't think any mods cause this?

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

**Comment by Electroblob77** [comment]
Ok... it's possible that the empowerment potion effect is not ending correctly for some reason. If you cast empowering presence and look in your inventory, does the potion effect icon disappear correctly when the time runs out?
This should be easy enough to reproduce, I'll try it myself and see what I can figure out.

**Comment by Electroblob77** [comment]
I can't reproduce this in my dev environment. Could you post some screenshots of this happening?

**Comment by Electroblob77** [comment]
I have managed to reproduce it thanks to another user experiencing the same issue. This only happens when using potency modifiers. Casting it using a master healing wand will produce the above effect. I will investigate why this is happening and hopefully get it fixed for the next update.

Edit: It's because empowering presence increases the potency of your spells, which then means when you cast it again it gives you a stronger potion effect, which means you can cast it a third time to get an even stronger effect, and so on until you have empowerment 100+! A bit of an oversight on my part, I will fix it for the next update.
