### ISSUE TITLE
NoSuchMethodError: getValuesCollection() crash on load

### ISSUE THREAD

**Issue by californiaimage** [Electroblob77/Wizardry#33]
Minecraft version: 1.12.2
Wizardry version: 1.12.2
Forge 14.23.3.2684:
Environment: Singleplayer

Issue details: Crash onload

Other mods involved: None, only mod loaded

Link to crash report (if applicable):

The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: net.minecraftforge.registries.IForgeRegistry.getValuesCollection()Ljava/util/Collection;

**Comment by Electroblob77** [comment]
I would have reopened the previous issue, you didn't have to make a new one!

Please post your _full_ crash report using gist or pastebin, there might be more information in there that will help me fix the problem. I will also try testing with that exact version of forge to see if I can reproduce the issue.

**Comment by LukeMageSlayerYT** [comment]
same problem

**Comment by ShadowPrimeX** [comment]
same issue here

**Comment by Electroblob77** [comment]
@LukeMageSlayerYT Please check your forge version is build 2611 or newer. If it is, could you post a crash report?

**Comment by ShadowPrimeX** [comment]
ye i updated forge and it worked

**Comment by Electroblob77** [comment]
Since nobody has commented on this for a while and everyone except californiaimage has managed to solve this by updating their forge, I'm going to go ahead and close the issue. (If anyone can _confirm_ that they are experiencing this issue with the latest version of Forge, please post a comment and I will reopen it.)
