### ISSUE TITLE
about "loaded a new chunk"

### ISSUE THREAD

**Issue by GoblinCwl** [Electroblob77/Wizardry#338]
Minecraft version: 1.12.2
Wizardry version: 4.2.7

Question details:
I think I should show you this?

`[17:31:27] [Server thread/WARN] [FML]: Electroblob's Wizardry loaded a new chunk [322, 313] in dimension 0 (overworld) while populating chunk [321, 313], causing cascading worldgen lag.
[17:31:27] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.`

**Comment by Electroblob77** [comment]
Occasionally this happens because the world generator spills into a new chunk. I managed to remove most of this in the 4.2 update but occasionally it still happens. It's nothing to worry about as long as worldgen isn't being super slow for you. [Here's a reddit post about it](https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/?ref=share&ref_source=embed&utm_content=body&utm_medium=post_embed&utm_name=26dd41bdcea6493590f00d8b772f2e35&utm_source=embedly&utm_term=5x0twz) if you're interested.
