### ISSUE TITLE
bugged textures

### ISSUE THREAD

**Issue by MasterMarkoJ** [Electroblob77/Wizardry#370]
Minecraft version: 1.12.2 
Wizardry version: 4.2.9 
Environment: Singleplayer 

Issue details: when traiding with wizzards gold indots and emeralds don't have an item texture

![bug 2](https://user-images.githubusercontent.com/59839585/75623709-210a1480-5bad-11ea-8d6f-ccc5a6021b2b.png)
![bug 1](https://user-images.githubusercontent.com/59839585/75623711-2b2c1300-5bad-11ea-9cd9-09ded0e4e72a.png)

**Comment by bigenergy** [comment]
+1

**Comment by Electroblob77** [comment]
I am aware of this, I will get a fix out as soon as I can.

**Comment by McBrettorrson** [comment]
I am experiencing the same problem, but others still seem to be able to trade. It won't even allow me to trade because of this :(

**Comment by HorribleNerd** [comment]
Yeah not just cosmetic, the bugged items seem to have a metadata of 32767 (SHRT_MAX), and thus they don't accept the normal items

**Comment by Paradimus** [comment]
When can you fix this bug? It sucks not being able to trade cuz my wand has been stuck to Novice. It's already at 4000+ over 2000

**Comment by McBrettorrson** [comment]
> When can you fix this bug? It sucks not being able to trade cuz my wand has been stuck to Novice. It's already at 4000+ over 2000

As suggested by other users (MC.Eternal subreddit) you can still make trades despite it not seeming to work otherwise. I have tested it and if you put in the exact number of items you need you can shift click the item to your inventory. It will not show up until after you close the inventory/leave the trade window and then reopen your inventory and it will be there. A temporary inconvenience but a quick fix for now.
