### ISSUE TITLE
Small oddities with spawned Wizards (a couple apply to Worldgen wizards as well)

### ISSUE THREAD

**Issue by hanleybrand** [Electroblob77/Wizardry#38]
Minecraft version: 1.12.2 
Wizardry version: 4.1.1 
Environment: Singleplayer - probably also MP

Issue details: Wizards have a small cosmetic/nomenclature issue* - at least as far as professions, they seem to show up as normal EntityVillager. It's only obvious when mods like Waila/Wayla are being used, but I also ran into a little weirdness when using the summon command with custom nbt (unfortunately I apparently overwrote the /summon command that caused the wizard to offer normal villager trades, which was a weird thing but I'm assuming I must have done something like set an NBT value the WizardEntity doesn't support which caused it to revert to being a villager? I dunno )

I'm no expert on java or forge, but this issue is probably due to EntityWizard extending EntityVillager. The "easy" solution seems to be to create & register a VillagerProfession and VillagerCareer to assign to EntityWizard.

I'm not sure if possibly being able to bork an entity with the summon command should even be worried about, since the summon command is kind of on the person doing it. 

Other mods involved: [only list mods that are relevant to the problem]

Other mods don't cause this issue, but it's possible that players wouldn't notice if they don't have a Waila/Wayla style mod active.

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]

No crashing.

**Comment by Electroblob77** [comment]
A couple of tests to narrow down the problem: If you open the trading GUI, do the wizards show up with villager profession names? What happens if you type `/say @e[r=5]` when you're standing next to a wizard?

In terms of the code, I might make it so `EntityWizard` implements `IMerchant` instead of extending `EntityVillager`, villager stuff has changed quite since I first wrote the wizard class and it's not as suitable as it was before.
