### ISSUE TITLE
Blacklist Config for Mind Controllable Targets (Mind Control Spell)

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#39]
Minecraft Version: 1.12.2
Wizardry Version: 4.1.1

**Description**: When using mind control against certain custom mobs that uses special behavior usually ends up causing an erratic outcome. **I've had some custom mobs from doing nothing to crashing the game and rendering that world broken forever when they're being mind controlled. (Aka Ticking Entity Crash)**

Maybe there could be a configurable option to blacklist certain mobs that can't be mind controlled? 

**Cause at the moment, Only Bosses, Mini Bosses, and wizards (Evil Only?) are the only Mobs that can't be mind controlled. And doesn't seem to be an option to add custom modded mobs yet.**

Without any other mods involved, the only mob that causes an erratic outcome when being mind controlled is the evoker.

EX:

------------

#List of names of entities that are immune to mind control. (Bosses and Mini Bosses are automatically immune to Mind Control)
S:mobsimmunetomindcontrol 
\<
modid:custommobname
minecraft:evoker
\>

------------

**Comment by Electroblob77** [comment]
Interesting, all mind control does is set the mob's target so in theory it should work with any mob. I'll take a look at the evoker class and see what's going on. It's probably something to do with evokers having multiple different attacks. As for the modded mobs, do you have some examples of mobs that cause problems? And could you post an example crash report?

I will add a blacklist to the config anyway because pack makers might find it useful.

P.S. you can type arrows in markdown \<\> by typing backslashes before them, like this `\>`.

**Comment by Ghostrider231** [comment]
Only a couple of modded mobs that do nothing are the aether mobs, but for the ones that crash the game are the inventory pets' mobs. 

About the Evoker Mob, him attacking his own, "Vex Swarm" Minion Spell is rather ironic when he's being mind controlled by you. One of the more notable oddities I've mentioned.

ROTD dragons which I haven't tested it on them, but I feel some really interesting strange behavior may occur for them.

Inventory pets' Living Bed and Anvil causes a crash when they're being mind controlled.
The Aether's Cockatrice acts like it was mind tricked instead of mind controlled. So It does nothing and stand there.

Crash report example (Inventory Pets crash): https://pastebin.com/ix7z83F2

**Comment by Electroblob77** [comment]
Haha, never crossed my mind that the evoker would do that, that's kinda funny! I don't think inventory pets are the sort of entities that should be mind controlled so a blacklist option does indeed make sense. The mind control effect works like mind trick when there are no valid targets in range, so for some reason the cockatrice must not be finding any valid targets.

**Comment by Electroblob77** [comment]
The solution I'm going to go with is just to add the blacklist to the config for now. I actually think the evoker attacking its own minions sort of makes sense, but since that is a minor issue I will address it at a later date if I decide to change it at all. As for the inventory pets crash, I can't really see what's going on since it's not open source but a blacklist option would prevent crashes from happening for now.

**Comment by Electroblob77** [comment]
Closed in f72ed33
