### ISSUE TITLE
Spell Storage - AE2

### ISSUE THREAD

**Issue by Rithenar** [Electroblob77/Wizardry#392]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.9 [change as necessary]

Question details: This may be a bug but wanted to start with it as a question.  Lacking other storage options for books with different NBT, I set up a Modular Storage connected to my AE2 system with a Storage Bus and a Fuzzy Card. I assumed it would work just as with Enchantment books, however none of the Spell Books will go into the Storage Unit even though I have it set up with the highest priority.  I placed a book of each tier in case it was looking at that information but still doesn't work.  Is this intended?

Other mods involved: [if this question involves other mods, list them here]
AE2 rv6-stable-7
RFTools 7.73

**Comment by Electroblob77** [comment]
The difference between enchanted books and spell books is that enchanted books use NBT to store enchantments (as you pointed out), but spell books use metadata to specify which spell they are. I'm not super familiar with the advanced AE2 stuff so I don't know if you would need a different setup for metadata rather than NBT.

**Comment by Rithenar** [comment]
Hmmm...time to get creative :)  Thanks!
