### ISSUE TITLE
Indirect damage does not count as magic damage

### ISSUE THREAD

**Issue by SonicX8000** [Electroblob77/Wizardry#396]
Note:
Maybe 'enhancement' might not of been the correct tag, after doing some more testing of what actually boosts the spell damage.

-----

How do I go about explaining this... and also might not be the right place.

Wizardry Spells deals magic damage however some mods that can boost the magic damage dealt, such as Quality Tools & Advent of Ascension's Zargonite Armor... these don't appear to increase the damage for Wizardry's Spells as I assume that they don't see it as a magic attack.

Using Scaling Health's Debug Info to see what damage source the Wizardry Spells use... it says 'indirect_wizardry_magic', although I've only tested this with the Magic Missile & Thunder spells from a Magic Wand.

I used a Twilight Sceptre from the Twilight Forest mod and that uses the 'indirectMagic' damage source when attacking with it. It's damage is increased with both Quality Tools & AoA's Zargonite Armor.

With some testing between these two items, this is what I get. I'm using ToroHUD to view damage particles.

Magic Wand: Magic Missile
Source: 'indirect_wizardry_magic'
Damage: 3

Magic Wand: Magic Missile | Custom quality boosting Magic Damage by 50%
Damage: 3

Magic Wand: Magic Missile | Zargonite Armor which boosts Magic Damage by 10% per piece
Damage: 3

Magic Wand: Magic Missile | Both damage boosts from the Quality & Armor.
Damage: 3

-----

Twilight Sceptre
Source: 'indirectMagic'
Damage: 6

Twilight Sceptre | Custom quality boosting Magic Damage by 50%
Damage: 9

Twilight Sceptre | Zargonite Armor which boosts Magic Damage by 10% per piece
Damage: 8

Twilight Sceptre | Both damage boosts from the Quality & Armor.
Damage: 13

==========

I am not sure if it's the damage source that they don't see. Unless maybe it's not really magic?

EDIT
...well the thought of it not really being magic might've been correct.

AoA's Predatious Armor, which increases Ranged Damage by 10% per piece apparently increases the damage dealt from the Spells. Same thing with Quality Tools increasing the damage from spells if the quality was boosting Ranged Damage.

I also did a test with Potion Core by applying the True Shot II Potion, which increases range damage... and... that increased spell damage as well.

Would it be possible to have the damage be classed as Magic-Based instead of Ranged-Based?

**Comment by Electroblob77** [comment]
Sorry, seem to have missed this one. Could you post your wizardry version?

The damage source has its own name (`indirect_wizardry_magic`) so that mods can distinguish between spells and things like potions if they want to. However, it _is_ counted as magic damage, as you can see here: https://github.com/Electroblob77/Wizardry/blob/1.12.2/src/main/java/electroblob/wizardry/util/MagicDamage.java#L121

I've looked at AoA's github (unfortunately quality tools isn't open source) and as far as I can tell, the test it uses for magic damage should work just fine with it: https://github.com/Tslat/Advent-Of-Ascension/blob/08d0c2adf5a200209a230ad5664e8ab0d8c36414/source/utils/EntityUtil.java#L326

As well as all spells being magic damage, some spells are _also_ projectile (ranged) damage, magic missile being one example. Do the magic damage boosts work with non-projectile spells like arc?

**Comment by SonicX8000** [comment]
Version:
ElectroblobsWizardry-4.2.10-MC1.12.2

====

I just tested it with Arc and the Zargonite Armor Boosts the damage. Same with Quality Tools boosting damage and for a double check, using Magic Focus from Potion Core also boosts it.

Using Scaling Health to list damage sources... Arc uses 'wizardry_magic' source which anything magic related will boost that source. So 'indirect_wizardry_magic' is ranged-based which is why range related stuff affects it.

**Comment by Electroblob77** [comment]
That's helpful, I can see where the issue is now. I'll get it fixed for the next update, thanks.
