### ISSUE TITLE
Removing sigil spells

### ISSUE THREAD

**Issue by Xules01** [Electroblob77/Wizardry#40]
Minecraft version: 1.12.2   
Wizardry version: 4.1.1 
Environment: Server   

Issue details: One of the players placed a couple of fire sigils in their base while discovering spells.  He left it there for a few server reboots, I stopped by and he wanted to get rid of them, so he unfriended me.  Nothing happened when I walked across the sigil, even tried spawning a zombie to do the same.  

We have created new sigils and placed them on top of this non-functioning one.  Those worked fine, but did not overwrite the old one.  It is still there.     

How can I remove the sigil he placed.

Other mods involved: N/A

Link to crash report (if applicable):  N/A

**Comment by Electroblob77** [comment]
I think this issue is related to [this comment](https://minecraft.curseforge.com/projects/electroblobs-wizardry?comment=379) on curseforge. It's a cosmetic issue I think, I'll look into it. Thanks for reporting it.

**Comment by Ghostrider231** [comment]
Well, if you have cheats enabled in your world (single player/lan) or have OP rights in the server (multiplayer)
That bug can be workaround, by using: **/kill @e[type=ebwizardry:fire_sigil]**
Because I had a bug like that, except for frost sigils. 
What I use to get rid of the unremoveable sigils is the: **/forge entity list ebwizardry:*** command and then find the permanent sigil and then **/kill @e[type=ebwizardry:yoursigilentityhere]**

Fireball, Greater Fireball, and Wither skull spells also seem to stay in the world if you end up shooting them in the sky. Which could resulting in the server having to tick more unused entites/projectiles? Also, they were said to have a 'lifetime' tag, but wasn't used?

Although like the sigils, these could be removed as well. Notice these are vanilla entities, so any vanilla projectiles flying atm will also be removed as well.

For Fireball spell projectile: **/kill @e[type=small_fireball]**
For Greater Fireball Spell projectile: **/kill @e[type=fireball]**
For Wither Skull Projectile: **/kill @e[type=wither_skull]**

**Comment by Electroblob77** [comment]
Thanks for posting the workaround, this still shouldn't happen though so I need to try and fix it. Fireball, greater fireball and wither skull are all vanilla projectiles, and I've seen fireballs floating around doing nothing in vanilla before so I'm pretty sure that's a bug in vanilla Minecraft. The original issue with sigils is a bug with wizardry though.

**Comment by Electroblob77** [comment]
The problem turned out to be a core targeting method returning false when the caster was null, when it really ought to be returning true. It actually affected a whole load of things other than sigils, but because sigils do not despawn it was more noticeable. This is now fixed, so now you'll always be able to remove the sigil, though occasionally the caster may lose immunity to sigils they placed - in this case the sigil will behave as if it was placed using commands, e.g. `/summon ebwizardry:fire_sigil`. Why the caster did not save properly in this instance I do not know, presumably it had something to do with the server reboots you mentioned.
