### ISSUE TITLE
Hyperlink syntax error in handbook_zh_cn.json

### ISSUE THREAD

**Issue by TUsama** [Electroblob77/Wizardry#406]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]

Issue details: the game still crashed when opened the handbook in chinese environment. 

Link to crash report: https://paste.ubuntu.com/p/M7KvgzFdf4/

**Comment by Electroblob77** [comment]
The problem is exactly what it says: there's an unclosed hyperlink marker in the `handbook_zh_cn.json` file. Every hyperlink in the handbook is specified like this: `@target text@` or simply `@target@`, where `target` is the section or URL the hyperlink leads to, and `text` (if specified) is the text to display instead of the section/URL itself.

I can go through that file and fix any broken hyperlinks, but since you helped with the translations, feel free to do it yourself.

**Comment by TUsama** [comment]
i have checked the file, but i counldn't find any format error mentioned in the crashreport. And if i changed the code UTF-8 to GBK without any text changes, the crash never happend again.

**Comment by Electroblob77** [comment]
That's weird, I did change the encoding to GBK in 153ea74. Unless my IDE changed it back somehow?
