### ISSUE TITLE
Ice wraiths cause damage through walls, and possibly aren't despawning

### ISSUE THREAD

**Issue by Echoweaver** [Electroblob77/Wizardry#412]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.2.11

Question details: I have a base near a snow biome, and I've spent 2-3 days mining beneath my house while an ice wraith parks above me. The ice it throws damages through multiple walls.

It seems like a wraith ought to move on before this, and that stone or wood walls should provide some protection.

What's the thinking about this?

Other mods involved: Don't think this involves any other mods.

**Comment by Echoweaver** [comment]
I have a base near a snow biome, and I've spent 2-3 days mining beneath my house while an ice wraith parks above me. The ice it throws damages through multiple walls.

It seems like a wraith ought to move on before this, and that stone or wood walls should provide some protection.

What's the thinking about this?

**Comment by Electroblob77** [comment]
That's not right, it shouldn't go through walls! And ice wraiths should despawn in the daytime as well. I am aware that lightning wraiths do hit players through walls, that will be fixed. As for ice wraiths, I'll have to have a look into it, that's very strange behaviour. Thanks for reporting.

**Comment by TopPercentageRattata** [comment]
I got stuck in an 80+ death loop because of spamming rmb a lot during a lag spike with an undiscovered spell, spawned hundreds of lightning wraiths and storm elementals. None of those ever despawned, so maybe the ice wraith hes talking about was from a spell misfire as well.

**Comment by Echoweaver** [comment]
To be clear, the wraith wasn't going through the walls. The ice shards were. The wraith was outside my house, two walls away, but could clearly "see" me. It continued to attack. I went down into a mine and hung out at level ~15, where I couldn't hear or be reached. Then I came back up after most of a day, and it was still there throwing ice shards. I did this twice over 2-3 game days.

This was definitely happening in daylight.

I don't think I had attempted an unknown spell and had it misfire at this point. I built my house sort of close to an ice biome, and occasionally wraiths have drifted over. The last time it happened. the wraith's ice still came through the walls, but it drifted away about when I expected it to.

**Comment by Electroblob77** [comment]
I have done some testing, and I have managed to recreate damage through walls in the following situations:

1. Lightning wraiths can attack (using the arc spell) through walls, as I mentioned before this is a known issue that I am in the process of fixing
1. Ice/lightning wraiths and vanilla blazes seem to sometimes be able to _melee_ through 1-block thick walls if I stand right up against them, presumably a bug in vanilla
1. Anything can melee through a diagonal 1-block wall because the mob's hitbox pokes through
1. Ice wraiths and vanilla blazes can hit me with their projectiles through a diagonal 1-block wall for the same reason, either if I stand right up against the corner or the blaze/ice wraith is right up against the other side

I have been unable to recreate ice shards going through walls in any other way. In fact, the ice wraiths stop following me if I go behind a wall for too long, as you would expect any mob to do.

You should be able to get the wraith to despawn by going far enough away, much like normal mobs.

@TopPercentageRattata I assume they weren't behind a wall though, in which case it's just bad luck on your part 😬
