### ISSUE TITLE
Config is missing: spells and drop chances

### ISSUE THREAD

**Issue by Master-Henry2006** [Electroblob77/Wizardry#423]
Minecraft version: 1.12.2 
Wizardry version: 4.2.10
Environment: Server

Issue details: 

In the server's config file of ebwizardry I can't find the option drop chances which goes from 1 to 200. At the client I can change the value, but at this config file I can not see the option. 

In the folder config/ebwizardry is no possibilty to edit the spells like it had been mentioned in the changelog of version 4.2.4. Also the folder world/data/spells is empty. I looked in the changelogs, but I think the feature hadn't been removed. This bug also exists on my client. Editing the files in assets/ebwizardry/spells works, but I don't want to edit the code, because I fear damaging it heavily.

**Comment by The-Minecraft-Scientist** [comment]
I have this issue as well.

**Comment by Random-Scientist** [comment]
Technically, it is possible to configure those items, but you need to add a custom loot table on a per-world basis, so I would say there _is_ a workaround for this issue

**Comment by Electroblob77** [comment]
Both of these are intended behaviour.

The spell book drop chance config option was removed in wizardry 4.2 because the drop chance is now defined using loot tables. Forge does not delete old config options when the mod is updated, they will stay in your config file but they won't do anything.

In both `config/ebwizardry` and `world/data`, _you have to create the files/folders yourself_. This is because if they were generated automatically, they would stay in people's folders and overwrite any changes I make to the default ones when I update the mod. Read the wiki page carefully, it explains how to modify spell properties without editing the mod jar https://github.com/Electroblob77/Wizardry/wiki/Spell-Properties.

If you're still not sure, feel free to ask me and I'll walk you through it.
