### ISSUE TITLE
Crash with deobfuscated version

### ISSUE THREAD

**Issue by Dyskal** [Electroblob77/Wizardry#431]
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Wizardry version: 4.2.11
Environnement: Developpement / Client

Issue details: I'm trying to create an addon for EBWizardry and I need a deobfuscate version of your mod. I tried to deobfuscate your mod with BON-2.4.0.15 and I got a proper deobfuscated version of EBWizardry and it works with Idea, but if I try to launch the game, the game crash with this crash report. Can you create a working deobfuscated version of your mod, or can you help me for my problem. Thanks

Crash report:
https://pastebin.com/hifVB4fD

**Comment by Electroblob77** [comment]
You shouldn't need to deobfuscate the mod any more, Forge should do it for you (this is better because forge can then apply whichever MCP mappings you're using, rather than being stuck with the ones I used). The wiki has a tutorial on how to set up your workspace, it will take you through the process https://github.com/Electroblob77/Wizardry/wiki/Developing-Addons

Alternatively, you can use maven to do it for you. Have a look at the `build.gradle` file in the twilight forest spell pack for an example https://github.com/Electroblob77/TF-Spell-Pack/blob/master/build.gradle#L86

**Comment by Dyskal** [comment]
ok thanks, i finally managed to attach the source with gradle

for your exemple, curseforge don't have the files for the lastest version (4.2.11)

**Comment by Electroblob77** [comment]
> for your exemple, curseforge don't have the files for the lastest version (4.2.11)

What do you mean by that? I no longer publish deobfuscated jars on curseforge because, as I said, they are no longer necessary.

Glad you got it working though.

**Comment by Dyskal** [comment]
no sorry, I just configured Maven Curseforge incorrectly
