### ISSUE TITLE
Electroblob's Armor not displaying properly

### ISSUE THREAD

**Issue by Sqweedgee** [Electroblob77/Wizardry#432]
Minecraft version: 1.12.2 
Wizardry version: 4.2.11
Environment: Server 

Electroblob's armor (along with some other mods like Better Animals +) not displaying properly, but armor for other mods (mowzies, atum) are displaying properly.

We're using Emoticons, which is likely what's causing the problem, but is there any way to fix this without removing the mod? Not sure why it's messing up the wizard hat and wolf cape, but not the Wrought Helm, for example. 

Any suggestions?

Modlist:
Better Animals + 
BetterFPS 
Corpse 
Electroblobs 
Emoticons 
Foamfix 
megaloot 
mowzies mobs 
phosphor 
tektopia
tinkers
vanilla fix

pictured is the correct wrought iron helm, the incorrect wizard hat skin, the incorrect wolf cape skin, and an example of what the wolf cape should look like.

https://imgur.com/NTNvQGm

**Comment by Electroblob77** [comment]
> Not sure why it's messing up the wizard hat and wolf cape, but not the Wrought Helm, for example.

Because the wrought helm uses a standard 64x32 texture, whereas the wizard armour uses 64x64. There's nothing I can do about this, the wizard armour simply won't fit in a standard 64x32 texture, and as you pointed out, it's not limited to wizardry. You'll have to ask the author of emoticons to support larger armour textures, sorry.

P.S. I know Mo bends used to have this problem but then fixed it, so it can be done.
