### ISSUE TITLE
Game fails to start (VanillaFix identified this mod as cause)

### ISSUE THREAD

**Issue by SpencerMeow** [Electroblob77/Wizardry#457]
Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.2.11 [change as necessary]

[crash-2020-06-08_14.02.53-client.txt]
https://github.com/Electroblob77/Wizardry/files/4748009/crash-2020-06-08_14.02.53-client.txt

**Comment by Electroblob77** [comment]
Just to confirm, is Baubles installed? Somehow it's detecting baubles is installed, but then failing to find the baubles slots.

**Comment by Tora-B** [comment]
It's in their crash log, but so is a bunch of other junk. They may have a mod that's repacked an old version of the Baubles API that doesn't have the charm slot. I'm always suspicious of conflicts when there are files with "(1)" or "(2)" and the like in a crash log, because it means they've just dumped a bunch of files in the mods folder, and Forge may load code from them, but not indicate that it's done so in the crash log. There's a decent chance there's something for the wrong version of Minecraft in there that's trashing Baubles. CoFHLib, maybe?

**Comment by Electroblob77** [comment]
Hmm, good spot. I just saw the 1.5.2 version number for Baubles and assumed it was okay (that's the minimum requirement for wizardry), but I wasn't looking that closely! @SpencerMeow in that case, try removing all mods with a (1) or a (2) in the filename and re-downloading fresh up-to-date versions of them.
