### ISSUE TITLE
On the bugs of posession magic

### ISSUE THREAD

**Issue by ornleaff** [Electroblob77/Wizardry#459]
Minecraft version: 1.12.2
Wizardry version: 4.2.11 
Environment: Singleplayer

Hello, Electroblob.I found a serious bug during the single machine test. When I cast the possession magic on decoy, it will cause a crash. I hope to fix it in the next version.
In addition, I found an interesting bug. First I used slow time magic, then I used possession magic and got away immediately. The attached creature will get the slow time effect permanently. The player will be slowed down by this creature. This is a very interesting bug. I hope it can be preserved.
My English is not very good. I hope you can understand it. Thank you :)

**Comment by Ghostrider231** [comment]
I'm getting the possession crash as well when I use them of decoys, except it only happens when I go into third person mode.

I don't know if possession has some sort of blacklist like the mind control spell has, but could useful for modpack makers.

**Comment by TUsama** [comment]
can you provide a crash report? this can help blob to figure that out more easily.

**Comment by ornleaff** [comment]
> 您可以提供崩溃报告吗？这可以帮助Blob更轻松地解决这一问题。

Certainly.

[crash-2020-06-11_10.32.03-client.txt](https://github.com/Electroblob77/Wizardry/files/4762229/crash-2020-06-11_10.32.03-client.txt)

**Comment by Electroblob77** [comment]
What's happening there is it's trying to render you as another player... which I guess the game doesn't like. Anyway, possession should not work on decoys (since they're just an 'illusion') so I will prevent that for the next update.

As for slow time, that's an interesting one. When possession ends, any potion effects you had while possessing get transferred to the mob you possessed, but slow time is only designed to work with players so that must be causing the problem. Again, I'll have to make this a special case so the slow time effect doesn't get transferred.
