### ISSUE TITLE
Selected Spell GUI renders along three blank buttons in f5 when Stellar API is installed

### ISSUE THREAD

**Issue by Ghostrider231** [Electroblob77/Wizardry#47]
Minecraft version: 1.12.2  
Wizardry version: 4.1.1
Environment: Cilent

Issue details: Holding a wand in mainhand or offhand which shows your selected spell also shows three blank buttons when in f5/thirdperson mode whenever Stellar API is installed.

Other mods involved: Stellar API (1.12.2-0.4.2.9)

**Comment by Abastro** [comment]
Hello, I'm the author of the Stellar API mod. I heard that push/pullAttribs are broken.
https://github.com/MinecraftForge/MinecraftForge/issues/1637

This might be the issue here. Do you need it?
https://github.com/Electroblob77/Wizardry/blob/7db3151d8abe3af8a2da3cf6bf869d822a8cadaf/src/main/java/electroblob/wizardry/client/GuiSpellDisplay.java#L125

**Comment by Electroblob77** [comment]
Someone on the discord server mentioned that push/pull attrib is broken, and it's almost certainly the cause of this issue. I'm going to go through removing them all for the next patch. This may be the cause of #46 as well.
