### ISSUE TITLE
Garbled in handbook_zh_tw.json 

### ISSUE THREAD

**Issue by HIN0815** [Electroblob77/Wizardry#528]
Minecraft version: 1.12.2
Wizardry version: 4.3
Environment: Singleplayer/LAN game/Server [delete as necessary]

Issue details: I found garbled characters in the text file handbook_zh_tw.json , it will make player cannot use zh_tw.

Link to crash report (if applicable): 
![image](https://user-images.githubusercontent.com/43261589/97210718-f5e9ca80-17f8-11eb-9a05-f1643b2e7fc8.png)

**Comment by Electroblob77** [comment]
Okay, I'll have a look at it. Thanks for reporting.

**Comment by TUsama** [comment]
In the previous version, the handbook has a problem that will crash your game when you open the book if the corresponding language file doesn't code as correct text encoding. I don't know what code has been used to code zh_tw, as for zh_cn, we use GBK.

But after a bug fix(https://github.com/Electroblob77/Wizardry/pull/479), you now should change the code to UTF-8, otherwise it will not work(or directly cause the game crash).

**Comment by Electroblob77** [comment]
Assuming PR #568 deals with this.
