### ISSUE TITLE
Offset mobs

### ISSUE THREAD

**Issue by slayerhoodz** [Electroblob77/Wizardry#529]
Minecraft version: 1.12.2
Wizardry version: 4.3 
Environment: Singleplayer and Server 

Issue details: If a player has an arrow stuck in them, nearby entities (namely mobs but also items from what I can tell) are offset from their actual position when viewed in 3rd person. These offsets appear to other people

![](https://cdn.discordapp.com/attachments/461653775933767692/769404984436457472/unknown.png)

Other mods involved: none

**Comment by Electroblob77** [comment]
Thanks for posting. Some GL transformations must somehow be left dangling when the arrow is rendered (probably to do with the mirage spell), I'll look into it.

**Comment by nerve20** [comment]
Just an FYI this also happen on first person when opening inventory screen as the player model is also rendered there. This causes the inventory screen to be bugged out, as in all the items are invisible.

**Comment by Electroblob77** [comment]
> Just an FYI this also happen on first person when opening inventory screen

Yes, that is issue #530. They are caused by the same bug but since the effects are different I've left both issues open for clarity. This is actually not to do with the mirage spell as I first thought, it's caused by the player animation system (of course... it seems to cause nearly all the bugs 😅). I've identified the cause and will fix shortly.
