### ISSUE TITLE
Crash and/or no entity when throwing a bomb item, such as electro bomb, or fire bomb

### ISSUE THREAD

**Issue by ghost** [Electroblob77/Wizardry#559]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.1 [change as necessary]
Environment: Client Side when updating lighting and chunks

Issue details: When I right click to throw one of these bomb projectiles, it does not spawn, and Vanilla Fix shoots out the following crash log.

Other mods involved: Thoroughly tested, is an actual issue with Wizardry itself.

Link to crash report (if applicable): 
[crash-2020-11-19_13.16.31-server.txt](https://github.com/Electroblob77/Wizardry/files/5566973/crash-2020-11-19_13.16.31-server.txt)

**Comment by Electroblob77** [comment]
I've tested this and it does not happen in my installation with any of the throwables. Same version, singleplayer world, survival or creative. Can you _confirm_ that this happens with no other mods installed? Even when crash reports look like they only involve one mod, it doesn't mean others weren't involved.

**Comment by ghost** [comment]
JEI...Optifine...

**Comment by ghost** [comment]
I can confirm yet again, that at least with Wizardry and Optifine installed, it crashes.

**Comment by ghost** [comment]
This is probably due to the fact you are forcing the bomb to add light to chunks.  can you add a configuration to disable this custom lighting code so optifine behaves with it?

**Comment by GradiusLover2000** [comment]
Sent from Mail for Windows 10 From: ElectroblobSent: 04 December 2020 18:39To: Electroblob77/WizardryCc: Colin James Wood; AuthorSubject: Re: [Electroblob77/Wizardry] Crash and/or no entity when throwing a bomb item, such as electro bomb, or fire bomb (#559) I've tested this and it does not happen in my installation with any of the throwables. Same version, singleplayer world. Can you confirm that this happens with no other mods installed? Even when crash reports look like they only involve one mod, it doesn't mean others weren't involved.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Electroblob77** [comment]
> This is probably due to the fact you are forcing the bomb to add light to chunks. can you add a configuration to disable this custom lighting code so optifine behaves with it?

I am doing no such thing. Besides, the original crash you posted is server-side. Please post the new crash so I can check it is the same.

I don't know how much you know about Java, but here's a technical explanation of what's going on:

The crash is happening because the thrower is somehow `null` in vanilla's method for aiming the entity. However, if you follow the call stack back up you'll see that if it was `null` in my code, it would have crashed there before it ever got to vanilla code. The only possible explanation is that another mod has used ASM to mess with the vanilla method `EntityThrowable#shoot` and set the thrower to `null` before it gets aimed. Why any mod would do that is beyond me, but as usual Optifine is a suspect.

You could try turning off dynamic lights for entities in Optifine and see if that makes a difference. Other than that, please try removing mods one by one until the issue disappears, so I can narrow down which mod is causing the problem.

**Comment by ghost** [comment]
There is no client crash log.  It only shows a server side crash.

And I swear I remember this lighting "animation" effect when the bomb explodes.  But I guess that was some weird dream I had...

**Comment by Electroblob77** [comment]
> You could try turning off dynamic lights for entities in Optifine and see if that makes a difference. Other than that, please try removing mods one by one until the issue disappears, so I can narrow down which mod is causing the problem.

Did you try either of these? They will help me to narrow down the cause of the problem.
