### ISSUE TITLE
Using Ice Spells causes significant graphical issue in game. 

### ISSUE THREAD

**Issue by lunarmaximum** [Electroblob77/Wizardry#563]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.3.1 
Environment: Server/singeplayer

Issue details: 
One of my server friends attempted to use the ice spells in the nether against the lycanite mobs from lycanite mod but it caused severe graphic issues (ie screen glitching out and going black). Even when I tried to pull up the "esc" to exit out the game, that menu did not show up bc of the blacked out screen. I had to exit the entire game to resolve the issue. 

Other mods involved: Lycanite Mod 

Not crashing, just graphic glitches blacking out the screen and other's people screen. I think it happens when an ice spell is used to kill the mob. 

Edit: I also tested it in single player mode and the problem persists as well. Only occurs after damaging them with any ice spells.

**Comment by Electroblob77** [comment]
Looks like the same issue that was fixed in PR #312, sure enough I've somehow managed to lose that fix when reorganising the code:
https://github.com/Electroblob77/Wizardry/blob/14e481a71dd91462ce3a137737e6c66b672e371c/src/main/java/electroblob/wizardry/client/renderer/entity/layers/LayerTiledOverlay.java#L146

Thanks for reporting, I'll get this fixed for the next patch.

**Comment by AkaiRozu** [comment]
oh.
