### ISSUE TITLE
MOD CONFLICTS

### ISSUE THREAD

**Issue by guiggonator** [Electroblob77/Wizardry#579]
Minecraft version: 1.12.2 
Wizardry version: 4.3.1
Environment: Singleplayer/LAN game/Server 

Issue details: I was creating a modpack for minecraft. Obviosly it had to have my favorite mod: electroblob's wizardry, but the modpack contained morph and when i tried to use morph something went wrong and said that electroblob's wizardry was responsible. Can you look and see what is the problem please? I really want to create a modpack with that mod before christmas

Other mods involved: Morph (maybe ichunutil)

[crash-2020-12-18_18.45.35-client.txt](https://github.com/Electroblob77/Wizardry/files/5717584/crash-2020-12-18_18.45.35-client.txt)

**Comment by Naigaru** [comment]
Disable spellcasting animations in electroblob wizardry (client settings - second from bottom), I believe its just the general bug with galaticraft's model rendering which messes things up. If after that the issue persists, update the issue with a new crash log.

**Comment by guiggonator** [comment]
ok, thank you!

**Comment by guiggonator** [comment]
its working, thank you again!!!

**Comment by Electroblob77** [comment]
That's kind of expected, morph does of course mess with the player model a lot so it's unsurprising that it conflicts with spellcasting animations. I'll leave this open since I'd like to try and make the animations compatible with as many mods as possible, or at least stop them from crashing when incompatible. Thanks for reporting.

**Comment by Electroblob77** [comment]
Fixed in 4.3.2
