### ISSUE TITLE
Fireball Config broken

### ISSUE THREAD

**Issue by Shibva** [Electroblob77/Wizardry#601]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 [change as necessary]  
Wizardry version: 4.3.2 [change as necessary]
Environment: Singleplayer

Issue details: The config is enables and the firebals are using the wizardy fireballs instead

Other mods involved: 
[Uploading Pack.zip…]()

![image](https://user-images.githubusercontent.com/38770780/104389734-2264d700-550a-11eb-8551-3a98c4e523fb.png)

**Comment by Shibva** [comment]
and may I request for the ones shot by ghast to be abel to kill them regardless if the setting is set to true

because it fails to even harm then, making the advancment "Return to Sender" impossable to acomplish when set to true

**Comment by Electroblob77** [comment]
Everything is working as intended on my installation. Unfortunately, due to an oversight in the vanilla code for the ghast I can't easily make wizardry fireballs damage them.

Your problem is happening because you did not delete your old config file when you updated wizardry. See how the config option is in funny lower/uppercase? That means it is reading the old leftover option directly from the config file, which does nothing. There should be a new version of this option under Tweaks Settings, change that and it will work as expected.

**Comment by Shibva** [comment]
oh, why thankss for the info, though you expect for the config to update itself if a new one, Though regardless, thankyou

**Comment by Electroblob77** [comment]
The config does update itself, you were just editing the old option instead of the new one. The old option doesn't get deleted in case you want to copy your settings over. That's just how Forge does it.

Because of this issue, I decided to add a warning so people know if they have old options lying around.

**Comment by Shibva** [comment]
good idea

**Comment by Shibva** [comment]
oh yeah
on another note the fireballs seem to cause issues when they are used by the UR ghast
they hit one another and explode, usualy sending one fireball insead of the barage

that sort of breaks the fight, can you look into that so the fight wont do that anymore wiht the replaced projectiles?

Thanks in advance
