### ISSUE TITLE
Still not supporting Player-remodeling mod

### ISSUE THREAD

**Issue by B-Wither** [Electroblob77/Wizardry#625]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/CONTRIBUTING.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: 4.3.4 
Environment: Singleplayer

Issue details: As I mentioned #539 , with More Player Models mod, animation is not working.
Maybe Custom Player Model don't works too.
There seems to be a way for other mod models such as Quark and Mowzie's Mobs, and I think you've tried it, but it didn't work in my game.
Other mods involved: More Player Models

**Comment by MagmaSlime123** [comment]
Unless Eletroblob adds compat. for other mods that edit the player model, then support for this will never happen.

**Comment by B-Wither** [comment]
As mentioned in #551, he was trying to make animation compatible. In fact, that compatibility doesn't seem to work in 4.3.4.

**Comment by MagmaSlime123** [comment]
I know.

**Comment by Electroblob77** [comment]
Okay, thanks for letting me know. As a result of the fix for #551, some mods that edit the player model _are_ now compatible, Galacticraft being one example. This works because Galaticraft is nice enough to add its custom models to `RenderManager#skinMap`, which means I can access them and fiddle around with them as necessary. I suspect that More Player Models does not do this, meaning I am unable to access its custom player models to make the edits needed. However, I can't be sure of this because that particular mod is not open-source.

**Comment by B-Wither** [comment]
I see.
Speaking of open source mods, how about take a look at Quark's emote feature? I think it was animation compatible with other mods.
I validated it with the Custom Player Model, but Wizardry's animation wasn't applied, but Quark's emotes were done.

**Comment by MagmaSlime123** [comment]
@Electroblob77 You could just decompile the MPM mod.

**Comment by Electroblob77** [comment]
@MagmaBro123 True, but even if I confirm the suspected problem there is nothing I can do about it unfortunately.

**Comment by MagmaSlime123** [comment]
Ugh.
