### ISSUE TITLE
Summoned entities (wraith etc) behave strangely/inconsistently with Lycanite's Mobs pets

### ISSUE THREAD

**Issue by Jackiecrazy** [Electroblob77/Wizardry#63]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Singleplayer

Issue details: 
Expectation: summoned minions fight alongside pets and Lycanite's minions
What actually happened: varies from minion to minion. Iron golem functions exactly like a vanilla one so RIP tamed chupacabra 2018-2018. Shadow wraith seems to indiscriminately attack everything, skeleton legion completely ignored a chupacabra that wasn't tamed, in general quite chaotic. They also don't attack what I attack, so it's a bit difficult to coordinate.

Other mods involved: Lycanite's Mobs

**Comment by Electroblob77** [comment]
Hmmm, right. Firstly, the iron golem is indeed different for now, though this will probably change in future. As for the others, they all effectively use the same AI so must behave the same (with the one exception that minions with melee attacks will ignore flying mobs), so it's strange that you're seeing different behaviour. It would be worth adding the mobs in question to the summoned creature targets whitelist in the config file and seeing if that makes any difference.

I will have a look at how summoned creatures (and more generally, the ally/targeting system) interact with tamable creatures, like wolves and such like. However, there's no guarantee this will affect tamable creatures from other mods, because that depends on whether they extend the vanilla system or not.

**Comment by Electroblob77** [comment]
Possibly fixed in the 4.2.0 release. If not, please reopen this issue.
