### ISSUE TITLE
Zombie awareness

### ISSUE THREAD

**Issue by DaniilGa** [Electroblob77/Wizardry#631]
when I summon zombies, zombies attack me even though I just summoned them.
This bug works if zombie awareness is installed.

Other mods involved: zombie awareness

thank you very much for trying so hard)

**Comment by Electroblob77** [comment]
I would assume this is because zombie awareness messes with zombie AI. If you haven't already, try turning off minion revenge targeting in the config. If not, you may be able to blacklist mobs from being affected by zombie awareness, wizardry's zombies actually have the id `ebwizardry:zombie_minion`.

**Comment by Sulferix** [comment]
can confirm this issue on my end, also is an issue with skeletons. the recommended fix here helped but did not solve the problem. also i dont know where to blacklist mobs in zombie awareness. in the zombie awareness config, the ebw mobs are all set to false anyways.

**Comment by WinDanesz** [comment]
Refer to the discord server for more help as this was discussed there a few times, if you still have this issue.
