### ISSUE TITLE
Updating to 1.16

### ISSUE THREAD

**Issue by Dima280807** [Electroblob77/Wizardry#654]
Can I update this mod to new versions, at least for myself, and if so, how?

**Comment by Electroblob77** [comment]
I'm hoping to set up a 1.16 development branch on this github repo soon, so that people can contribute by forking the repo and submitting PRs. I'll make an announcement when this happens. However, you're free to work on it yourself before I do this, I can always merge it in later.

You'll need to set up a modding development workspace with Forge and your Java IDE of choice. If you've never modded before, I'd suggest trying to write a practise mod before you try to work on wizardry, otherwise it might be a bit overwhelming!

**Comment by Dima280807** [comment]
Thank you!
