### ISSUE TITLE
Refill wand mana via Evilcraft blood chest

### ISSUE THREAD

**Issue by flamechair** [Electroblob77/Wizardry#66]
Minecraft version: 1.12.2 
Wizardry version: 4.1.2 
Environment: Server

Issue details: Since wand mana is shown as the item's durability, any items that repair durability on items (Evilcraft's blood chest for example) can refill the wand's mana. This eliminates the need for finding crystal ore/crystal flowers.

Other mods involved: Evilcraft

Not sure if this would be considered a bug or intended, but I wanted to make you aware of it.

**Comment by Electroblob77** [comment]
I suppose I'd class it as an exploit rather than a bug. Either way, it's not intended, so ought to be fixed, or at least made optional. Do you happen to know if other items that use durability to represent something else (like a battery from IndustrialCraft or something) also behave this way? If not, it might be worth looking at how they stop it from happening.

**Comment by flamechair** [comment]
I have not been able to find any other mod item that this also happens too, TE capacitors simply aren't allowed to be placed in the chest.

**Comment by flamechair** [comment]
You could sell it as an integration with Evilcraft! Recharge you're wands with blood instead of mana because you're a bad person

**Comment by Electroblob77** [comment]
Fixed in the 4.2.0 release.
