### ISSUE TITLE
Forfeit mechanic not respecting claims.

### ISSUE THREAD

**Issue by jazoobio** [Electroblob77/Wizardry#672]
Minecraft version: 1.12.2
Wizardry version: 4.3.4
Environment: Server

Issue details: Forfeits from unidentified spells don't respect claims. Examples of this are Earth (spawning water, collapsing the ground), Fire (Spawning fire around), Ice (Spawning ice/snow).

Other mods involved: FTBUtilities

**Comment by WinDanesz** [comment]
The only solution what comes to my mind is to prevent casting unknown spells at all in claimed chunks.
(Otherwise, causing the spell cast attempt in claimed chunks to fail only if these special block-affecting forfeits happen would be exploitable as you could always avoid these forfeits by casting them in claimed chunks.)

**Comment by Electroblob77** [comment]
Actually I think this may be fixable. It seems that when I overhauled claim mod interaction I forgot to apply the changes to the forfeit class. For example, here's the code for the water forfeit:

https://github.com/Electroblob77/Wizardry/blob/486d55f34987adb36e2fea95cdf348b1437df160/src/main/java/electroblob/wizardry/misc/Forfeit.java#L405-L411

It should use the wrapper methods in `BlockUtils` instead of calling `setBlockState` directly. I'll go through them all and make that change for the next patch.
