### ISSUE TITLE
Worldgen Crash (OOM) with Sky Islands style terrain.

### ISSUE THREAD

**Issue by brisingraerowing** [Electroblob77/Wizardry#73]
Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Singleplayer

Issue details: Trying to create a world with a Sky Islands mod and EB Wizardry causes a crash when generating wizard towers

Other mods involved: [Sky Islands](https://minecraft.curseforge.com/projects/skyislands), though both [SkyLandsForge](https://minecraft.curseforge.com/projects/skylandsforge) and OTG: Skylands have the same crash as well.

Link to crash report (if applicable): [Crash Log](https://gist.github.com/BrisingrAerowing/182387aa4efe01a353057bdaa29f9ff3)

I have 10G RAM allocated.

**Comment by Electroblob77** [comment]
Interesting, thanks for reporting it. The fact that it happens with various different sky islands mods suggests that it's the actual shape of the world that's causing problems. My guess would be that a wizard tower is trying to generate at a x/z coordinate where there are no blocks at any height, and that is causing a loop somewhere. I'll have to have a closer look at the code to confirm this.

I assume this only happens when you actually use the sky islands world type? It would be worth confirming that having the mod installed but using a normal world type does not cause this problem.

**Comment by brisingraerowing** [comment]
Already tried that. It works with a normal world type, even if a skylands mod is installed.

**Comment by thephoenixlodge** [comment]
#24 is also this same problem, I added some extra info over there before noticing this one

**Comment by Electroblob77** [comment]
Yeah thanks for that, I've left this issue open and closed #24 because this is more descriptive.

For now, as a workaround if you're generating a sky islands world you can set the tower rarity config option to 0 to disable tower spawning. Obviously that's not ideal because you have to remember to turn it back on before generating other worlds, but for now it will at least avoid the crash.

**Comment by UpcraftLP** [comment]
@Electroblob77 as I pointed out in #24, it's easy to fix by just stopping after too many failed attempts here:
https://github.com/Electroblob77/Wizardry/blob/36f4728f3a86edf20238d25425386db5903dab42/src/main/java/electroblob/wizardry/WizardryWorldGenerator.java#L240-L254

fix could look something like this (replacing the while-loop with a for-loop):
```
int MAX_ATTEMPTS = 20;
for(int attempts = 0; flag && attempts < MAX_ATTEMPTS; attempts++) {
    //code
}
```

**Comment by Electroblob77** [comment]
Yes I know, thanks.
