### ISSUE TITLE
Out of memory Crash playing on server

### ISSUE THREAD

**Issue by AzureDoom** [Electroblob77/Wizardry#86]
Minecraft version: 1.12.2  
Wizardry version: 4.1.2 
Environment: Singleplayer/Server

Issue details: Player on my server is having this weird crash. It happens randomly. The user has given MC 2GBs of memory if that helps, though I do the same and don't get this issue. 

Link to crash report: https://gist.github.com/AzureZhen/423adece35223dd47722311343e2469b

**Comment by Electroblob77** [comment]
Hmmm...
```
at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.pre(GuiIngameRPGHud.java:505)
	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.drawElement(GuiIngameRPGHud.java:676)
	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.func_175180_a(GuiIngameRPGHud.java:132)
```
The player is using the RPG-HUD mod, which is firing the event wizardry uses to draw the spell GUI. I have just noticed that my GUI draw method subscribes to `RenderGameOverlayEvent` in general rather than one of its child classes, but I'd be surprised if this is what is causing the issue.

I suggest for now that you get the player to remove RPG-HUD (which I assume is only installed on that player's client) and see if the issue persists. Have they tried it in singleplayer? It shouldn't make any difference whether it's on the server or not.

**Comment by AzureDoom** [comment]
Yeah I've already gone ahead and removed RPG-HUD and he hasn't experienced this again.

**Comment by Electroblob77** [comment]
It's still worth me looking into at some point, I'd rather the two mods worked together.
