### ISSUE TITLE
I've ported this to 1.12...

### ISSUE THREAD

**Issue by 12foo** [Electroblob77/Wizardry#9]
Hi there,

I really wanted to play this, on 1.12, so I ported it for my own enjoyment. I don't want to be presumptuous about your own porting work you may already be doing, but I'm of course happy to submit a pull request. Otherwise I'll just be playing it until you release the official port. Thank you for a great mod and thank you for making it open source!

The port is here:
https://github.com/12foo/Wizardry/tree/1.12.2

Edited to add-- an apology for not coordinating with you in advance on this; I just thought 'let's give this a shot' yesterday and, well, it's somehow done now. Sorry.

**Comment by Electroblob77** [comment]
Hi! Firstly, thank you for taking the time to do this, I really appreciate any contributions that people make to the mod.

I can see you started with the 1.12.2 branch (which until just now was a placeholder copy of the 1.11.2 version), so no problems there. You probably noticed that Corail31, who helped me with the 1.11.2 port, has also done a port to 1.12.2, which I have just merged into that branch. However, I can see several issues you've fixed in your own commits, and there's a fair chance that Corail has missed some of them (although it's hard to tell because he did it all in one commit).

With that in mind, I think the best thing to do is to manually merge your port with Corail's and get the best of both, since Github won't be able to do it automatically, so if you could submit a PR that would be great. I'll still have to do some of my own testing to check things are working as they should.

Thanks again!

**Comment by 12foo** [comment]
Good morning,

sorry, I did not notice that, but that's what I get for rushing in like this. I'll have a look later and merge any appropriate changes on top of Corail's and then do a PR. I can see some differences in how we did things, so I'd like to first explain the difference and ask your preference in each case.

**Mod ID:** Corail keeps it at `wizardry` while I've moved to `ebwizardry` so as not to conflict with the other wizardry mod on 1.12 (as in your comment). I've also replaced most instances of the mod id in strings with `Wizardry.MODID` so it's easier to change again at a later date.

**Advancements:** Advancements are now defined in JSON files that are supposed to be overrideable by the user/server admin. Corail defines these with "impossible" triggers and triggers them hard-coded whenever appropriate, while I define a custom trigger for each one (meaning mine can actually be overridden by the user while Corail's will always trigger when the code says they should). I'm not sure how often users will actually want to override these, so my version may be overkill (it is slightly more cumbersome in code).

**Recipes:** As with advancements, recipes are now supposed to go into overrideable JSON files. Corail has kept them entirely in code while I have broken most of them out into JSON. Some, like mana flask charging, have to stay in code on account of custom effects. I figure most people will use CraftTweaker instead of JSON anyway, so you might prefer the convenience of having them all in code in one place.

The rest are mostly fixes like the spell sorting and the GUI tweaking and can just be ported over.

**Comment by Electroblob77** [comment]
Mod ID: Corail left it for me to do since it didn't directly affect the port, but if you've done it that saves me a job. Replacement in strings is long overdue as well (I've been doing them as and when I see them), so both of those changes will be useful.
Advancements: I'll have to take a look at them, but generally speaking I prefer to make stuff work like the vanilla system (the way you've done it). As you say, it probably doesn't make that much difference, and I will probably be rearranging wizardry's advancements a bit anyway.
Recipes: Similar to the advancements, I will probably go with the JSON for this, apart from the dynamic ones that have to be hardcoded.

**Comment by 12foo** [comment]
Since the pull request is merged, I'll go close this now. Looking forward to the eventual release!
