### ISSUE TITLE
Wizards get confused fighting a mob masher

### ISSUE THREAD

**Issue by mr2013** [Electroblob77/Wizardry#93]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2
Wizardry version: 4.1.2
Environment: Server

Issue details: Server/game crashes when you try to feed a wizard to a mob masher from Mob Grinding Utils

Other mods involved: Mob Grinding Utils

Link to crash report (if applicable): https://pastebin.com/LqxZrRd9

**Comment by Electroblob77** [comment]
I suspect the mob masher is 'pretending' to be a player (or more specifically, using what's called a fake player), which would make sense because then it would cause xp to drop. What has happened is a wizard has cast ice shroud, and when the wizard is attacked by the mob masher the game tries to give the fake player the frostbite effect, but this fails.

It's easy enough to test for a fake player so this should be a simple enough fix. Thanks for reporting.
