### ISSUE TITLE
Suggestions and ideas for this already awesome mod!

### ISSUE THREAD

**Issue by SirAron111** [Electroblob77/Wizardry#95]
1.	Configurable wands for people who like to use different spells on the same wand so not 65% extra max but maybe 40% fire/40% ice or so like depending on the ingredients used for crafting the wand or a special upgrade. (you could make special ingredient items that can be found/dropped like some kind of essence or magic catalyst and the normal wand crafted together with them makes the potency change like 2 ice and 1 fire with the wand makes a fire and ice wand with more % on fire than on ice but less than a pure fire wand)

2.	A better interface for the Wand Upgrades and the ability to change the upgrades like you can change the spells. (More celerity for what the wand upgrades actually do I get a lot of questions from my modpack users asking what do the upgrades for the wands do, the book don’t explain them etc.)

3.	Definitely more Spells these are the most awesome part of the mod and there are so many more things that can be made into spells XD

4.	More mod integration: especially for the armors for example special modifiers for tinkers armor mod or being able to integrate the armor effects from the wizard armors into armors like ender IO dark/ender armor to help Modpack makers with balancing.

5.	Have some of the mobs that can be summoned spawn as wild mobs as an option in the config (just a bit weaker). Would be nice to go into an ice biom and encounter an ice golem or to fight a shadow summon in the end (outer islands) etc.

6.	Somehow have your loot integrate into more modded loot tables for example ice and fire. Imagine fighting a dragon and then looting the chests in his nest and finding a nice spell or some wand upgrades. And not just gold nuggets.

That’s it for now loves your mod keep up the good work people playing my pack really like it to especially the visuals and spell diversity.

**Comment by Electroblob77** [comment]
1. Dual affinity has been discussed a little before, it's not off the cards but won't be in the next update. As with anything, I'd have to think about the a nice way to integrate it into the gameplay and lore/premise.
2. When you say 'better interface', what did you have in mind? Not being able to remove the upgrades was a deliberate design decision, because I wanted to make players think about how they spec their wands. However, I definitely agree that they need more explanation; this will be changing in the next update.
3. Of course! You can never have enough spells!
4. I'm working on a few mod integration features, although none involving armour as yet.
5. This is happening, although you'll need to go to specific locations to find them...
6. That's something you'll have to do! Use a resource pack to modify other mods' loot tables to include wizardry items. It's very simple to add the normal wizardry dungeon loot to any loot table, but with a bit more work you can customise almost everything.

**Comment by SirAron111** [comment]
Thx for hearing me out.

As for the better interface I was talking about how upgrades for the wand are not really visually appearing in any significant way. For the upgraded wand to master it changes shape but when adding an upgrade it doesn’t really appear in anyway noticeable. For example have a little glow effect like in mmos when upgrading weapons or a small orb swirling around the wand something like that. Didn’t actually mean the interface of the magic table!

But ye most of all it’s the missing upgrade descriptions or indications of the upgrades. For example since you can’t see the boarders of the spells you only really notice that the area of the aoe gets bigger with the area upgrade once it hits max lvl. A small item, like special goggles or glasses, monocle of some kind to see the affected areas would be an idea or a key bind.

Well anyway love the mod one of the best plain magic mods I have ever played with since ars magica.

**Comment by Electroblob77** [comment]
I've added the features I said I was working on above in the 4.2.0 release.
